### ISSUE TITLE
Found Bug!

### ISSUE THREAD

**Issue by vdanelia** [chuckfairy/VanillaQR.js#1]
Hello Mates, I found your QR Code Generator and testing it, seems very nice very smart and smooth, but bound some bugs..
For example it can't read Georgian font (UTF-8)

I also have a questions:

Q-1

How to add additional values like Vcard..
For example I need some information that QR to generate
1. My Site URL
2. My Site Email
3. My Site Phone Number
    So My Web Contact Information

I think I know why this QRCode not displayed Georgian UTF-8 Characters, there must be also option where user chan specify the Charset of the QR Code, There are 2 Standards (ISO/IEC 8859-1 and UTF-8)
If it supports Please Inform me how to set the option, I tried charset: "UTF-8", encoding: "UTF-8", but not worked...

Thank you In Advanced
Waiting for your reply as soon as possible

**Comment by chuckfairy** [comment]
Hello, can you give me a code sample / what URL and emails you are using for testing? Thanks!
